#!/usr/bin/env bash

moon run ../src/bin/main.mbt -- $1 -o /tmp/mbt.s
zig build-exe -target riscv64-linux -femit-bin=$2 \
  /tmp/mbt.s ../riscv_rt/zig-out/lib/libmincaml.a \
  -O Debug -fno-strip -mcpu=baseline_rv64

