#!/usr/bin/env bash

moon run ../src/bin/main.mbt -- --end-stage cps ./test_src/$1.mbt -o $1.cps
moon run ../src/bin/main.mbt -- --end-stage clops ./test_src/$1.mbt -o $1.clops
moon run ../src/bin/main.mbt -- ./test_src/$1.mbt -o $1.s


zig build-exe -target riscv64-linux -femit-bin=$1 \
  $1.s ../riscv_rt/zig-out/lib/libmincaml.a \
  -O Debug -fno-strip -mcpu=baseline_rv64

